# Generated by Django 4.0.5 on 2022-09-06 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_title', models.CharField(max_length=200)),
                ('post_description', models.TextField()),
                ('post_likes', models.IntegerField()),
                ('post_date', models.DateField(primary_key=True, serialize=False)),
                ('post_uesr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
