# Generated by Django 4.0.5 on 2022-09-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_posts_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_likes',
            field=models.IntegerField(),
        ),
    ]
