# Generated by Django 4.0.5 on 2022-09-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_posts_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_likes',
            field=models.IntegerField(default=0),
        ),
    ]
