# Generated by Django 4.0.5 on 2022-09-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_posts_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_likes',
        ),
    ]
