# Generated by Django 4.0.5 on 2022-09-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_posts_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
