# Generated by Django 4.0.5 on 2022-09-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_posts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
