# Generated by Django 4.0.5 on 2022-09-09 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_posts_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ManyToManyField(blank=True, default=None, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, default=None, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(blank=True, default=None, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
