# Generated by Django 4.0.5 on 2022-09-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_remove_followers_user_followers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='following',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='follower',
        ),
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
