# Generated by Django 4.0.5 on 2022-09-10 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_remove_followers_following_remove_followers_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='followers',
            name='user',
        ),
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
