# Generated by Django 4.0.5 on 2022-09-10 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_followers_follower_remove_followers_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='user',
        ),
        migrations.AddField(
            model_name='followers',
            name='followed_users',
            field=models.ManyToManyField(blank=True, default=None, related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
