# Generated by Django 4.0.5 on 2022-09-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_remove_followers_followed_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_liker', models.CharField(max_length=200)),
                ('post_like', models.CharField(max_length=200)),
            ],
        ),
    ]
