# Generated by Django 4.0.5 on 2022-09-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
