# Generated by Django 4.0.5 on 2022-09-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='post_like',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user_liker',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
