# Generated by Django 4.0.5 on 2022-09-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_alter_likes_post_like_alter_likes_user_liker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
