# Generated by Django 4.0.5 on 2022-09-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_alter_likes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='like_count',
            field=models.CharField(max_length=200),
        ),
    ]
